- project:
    check:
      jobs:
        - misty-unit-test
        - misty-integration-test

- job:
    name: misty-integration-test
    parent: init-test
    description: |
      Run integration tests of Misty
    run: playbooks/misty-integration-test/run.yaml
    vars:
      rvm:
        2.3.6
        2.4.3
        2.5.0

- job:
    name: misty-unit-test
    parent: init-test
    description: |
      Run unit tests of Misty
    run: playbooks/misty-unit-test/run.yaml
    vars:
      rvm:
        2.3.6
        2.4.3
        2.5.0
